spring:
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp.use_jdbc_metadata_defaults: false
        show-sql: true
        format-sql: true
        use_sql_comments: true
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/postgres?user=postgres&password=postgres
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
