spring:
  profiles:
    active: home
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp.use_jdbc_metadata_defaults: false
        show-sql: true
        format-sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

---
spring:
  profiles: home
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/postgres?user=postgres&password=postgres

---
spring:
  profiles: work
  datasource:
      url: jdbc:p6spy:postgresql://localhost:5432/postgres?user=postgres&password=admin