spring:
  profiles:
    active: home
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver

---
spring:
  profiles: home
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres

---
spring:
  profiles: work
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=admin